PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xbp: <http://xb.saltlux.com/schema/property/>
PREFIX xbr: <http://xb.saltlux.com/resource/>
PREFIX xbc: <http://xb.saltlux.com/schema/class/>
PREFIX xbv: <http://xb.saltlux.com/schema/vocab/>

SELECT ?X, ?Z
WHERE
{
  ?X rdf:type xbc:person_00006026 .
  ?Z rdf:type xbc:person_00006026 .
  ?X xbp:education ?Y .
  ?Z xbp:education ?Y .
  ?X xbp:relatedPerson ?Z .
}